import type { NotificationItem } from "@/features/notification/types/notification";

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 1,
    role: "CLIENT",
    type: "MATCHING",
    title: "AI 추천이 완료되었습니다.",
    description: "프로젝트에 잘 맞는 프리랜서 후보를 확인해 보세요.",
    createdAt: "방금 전",
    isRead: false,
    href: "/client/projects/1/candidates/1",
  },
  {
    id: 2,
    role: "CLIENT",
    type: "MATCHING",
    title: "김개발 님이 매칭 요청을 수락했습니다.",
    description: "수락된 매칭 요청의 상세 내용을 확인해 주세요.",
    createdAt: "1시간 전",
    isRead: false,
    href: "/client/projects/1",
  },
  {
    id: 3,
    role: "CLIENT",
    type: "NEGOTIATION",
    title: "새로운 AI 협상 제안이 도착했습니다.",
    description: "제안된 조건을 검토하고 협상을 이어가세요.",
    createdAt: "3시간 전",
    isRead: true,
    href: "/client/projects/1/negotiation/1",
  },
  {
    id: 4,
    role: "CLIENT",
    type: "CONTRACT",
    title: "계약서가 생성되었습니다.",
    description: "계약 내용을 확인한 뒤 서명을 진행해 주세요.",
    createdAt: "1일 전",
    isRead: true,
    href: "/client/projects/1/contracts/1",
  },
  {
    id: 5,
    role: "FREELANCER",
    type: "MATCHING",
    title: "새로운 매칭 요청이 도착했습니다.",
    description: "프로젝트 조건을 확인하고 요청에 응답해 주세요.",
    createdAt: "방금 전",
    isRead: false,
    href: "/freelancer/projects/1",
  },
  {
    id: 6,
    role: "FREELANCER",
    type: "NEGOTIATION",
    title: "클라이언트가 새로운 협상 조건을 제안했습니다.",
    description: "변경된 조건을 확인하고 협상을 이어가세요.",
    createdAt: "30분 전",
    isRead: false,
    href: "/freelancer/projects/1/negotiation/1",
  },
  {
    id: 7,
    role: "FREELANCER",
    type: "CONTRACT",
    title: "서명할 계약서가 도착했습니다.",
    description: "계약 내용을 확인한 뒤 서명을 진행해 주세요.",
    createdAt: "2시간 전",
    isRead: true,
    href: "/freelancer/contracts/1",
  },
  {
    id: 8,
    role: "FREELANCER",
    type: "MESSAGE",
    title: "새로운 메시지가 도착했습니다.",
    description: "클라이언트가 보낸 메시지를 확인해 주세요.",
    createdAt: "1일 전",
    isRead: true,
    href: "/chat",
  },
];
