import type { RecommendedCandidate } from "@/features/matching/types/candidate";

export const RECOMMENDED_CANDIDATES: RecommendedCandidate[] = [
  {
    id: 1,
    name: "김개발",
    role: "프론트엔드 개발자",
    careerYears: 7,
    introduction: "사용자 경험과 제품의 완성도를 함께 고민하는 프론트엔드 개발자입니다.",
    matchScore: 96,
    rating: 4.8,
    reviewCount: 17,
    level: "시니어",
    availableFrom: "즉시 가능",
    workStyle: "재택 · 주 5일",
    desiredRate: "월 6,500,000원",
    skills: ["React", "Next.js", "TypeScript", "Zustand"],
    strengths: ["대규모 서비스 운영 경험", "디자인 시스템 구축", "원활한 협업과 문서화"],
    recommendationReasons: ["요구 스킬 97% 일치", "경력 조건 충족", "재택 근무 선호", "시작 가능일 일치", "유사 프로젝트 3건"],
    careers: [
      { company: "테크 스튜디오", role: "시니어 프론트엔드 개발자", period: "2022.03 - 2025.07", description: "B2B SaaS 제품의 프론트엔드 아키텍처 개선과 디자인 시스템 구축을 담당했습니다." },
      { company: "커머스 랩", role: "프론트엔드 개발자", period: "2019.01 - 2022.02", description: "월간 활성 사용자 30만 규모 커머스 서비스의 주문·결제 화면을 개발했습니다." },
    ],
    projects: [
      { title: "기업용 프로젝트 관리 서비스", period: "2024.01 - 2025.06", role: "프론트엔드 리드", description: "업무 대시보드와 실시간 협업 기능을 설계하고 공통 컴포넌트를 구축했습니다.", skills: ["Next.js", "TypeScript", "WebSocket"] },
      { title: "커머스 모바일 웹 리뉴얼", period: "2021.02 - 2021.11", role: "프론트엔드 개발", description: "핵심 구매 여정의 성능과 접근성을 개선했습니다.", skills: ["React", "React Query", "Storybook"] },
    ],
    education: "한국대학교 컴퓨터공학과 졸업",
    status: "recommended",
  },
  {
    id: 2,
    name: "이서연",
    role: "프론트엔드 개발자",
    careerYears: 5,
    introduction: "빠르게 검증하고 안정적으로 확장할 수 있는 웹 제품을 만듭니다.",
    matchScore: 92,
    rating: 4.7,
    reviewCount: 12,
    level: "미들",
    availableFrom: "2주 이내",
    workStyle: "혼합 · 주 5일",
    desiredRate: "월 5,800,000원",
    skills: ["React", "TypeScript", "Tailwind", "GraphQL"],
    strengths: ["빠른 프로토타이핑", "성능 최적화", "백엔드 협업 경험"],
    recommendationReasons: ["요구 스킬 84% 일치", "경력 조건 충족", "재택 근무 선호", "시작 가능일 일치", "유사 프로젝트 1건"],
    careers: [{ company: "프로덕트 메이커스", role: "프론트엔드 개발자", period: "2020.04 - 2025.06", description: "핀테크와 예약 플랫폼의 웹 프론트엔드 개발을 담당했습니다." }],
    projects: [{ title: "예약 관리 플랫폼", period: "2023.05 - 2024.12", role: "프론트엔드 개발", description: "예약 캘린더와 운영자 대시보드를 개발했습니다.", skills: ["React", "TypeScript", "Node.js"] }],
    education: "페어링대학교 소프트웨어학과 졸업",
    status: "requested",
  },
  {
    id: 3,
    name: "박지훈",
    role: "웹 프론트엔드 개발자",
    careerYears: 4,
    introduction: "명확한 인터랙션과 반응형 UI 구현에 강점이 있습니다.",
    matchScore: 89,
    rating: 4.9,
    reviewCount: 21,
    level: "시니어",
    availableFrom: "1개월 이내",
    workStyle: "상주 · 주 5일",
    desiredRate: "월 6,200,000원",
    skills: ["React", "Next.js", "JavaScript", "TanStack Query"],
    strengths: ["반응형 웹 구현", "UI 디테일", "디자이너 협업"],
    recommendationReasons: ["요구 스킬 91% 일치", "경력 조건 충족", "협업 평가 우수", "시작 가능일 일치", "유사 프로젝트 2건"],
    careers: [{ company: "인터랙션 웍스", role: "웹 개발자", period: "2021.07 - 현재", description: "브랜드 웹과 고객용 서비스 화면을 개발했습니다." }],
    projects: [{ title: "고객 상담 포털", period: "2023.08 - 2024.04", role: "프론트엔드 개발", description: "상담 현황과 고객 관리 화면을 반응형으로 구축했습니다.", skills: ["Next.js", "JavaScript", "CSS"] }],
    education: "오이대학교 정보통신학과 졸업",
    status: "accepted",
  },
];

export const getRecommendedCandidate = (candidateId: number) =>
  RECOMMENDED_CANDIDATES.find((candidate) => candidate.id === candidateId);
